apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-detection-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: object-detection
  template:
    metadata:
      labels:
        app: object-detection
    spec:
      containers:
        - name: object-detection
          image: object-detection:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: production

          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "500m"
