apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-detection-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: object-detection
  template:
    metadata:
      labels:
        app: object-detection
    spec:
      containers:
        - name: object-detection
          image: mhaa0005/object-detection:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000

          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "500m"
