apiVersion: v1
kind: Service
metadata:
  name: object-detection-service
spec:
  selector:
    app: object-detection
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
  